server:
  port: 8081

spring:
  # Thymeleaf配置
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
  #  数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/business_platform?characterEncoding=utf8&autoReconnect=true&serverTimezone=PRC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# 权限校验相关信息
permission:
  secret-key: X0g1UAH1Gp5cDvIiEVf0bvAuHeFj7e8t
  subject: BUSSINESS-PLATFORM
# 平台工具相关
utils:
  thread-utils:
    core-thread-size: 4
    max-thread-size: 8
    keep-alive-time: 1000
