server:
  port: 8081

spring:
  # Thymeleaf配置
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
  #  数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/business_platform?characterEncoding=utf8&autoReconnect=true&serverTimezone=PRC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19970911fh
    type: com.zaxxer.hikari.HikariDataSource
  # reid配置
  redis:
    # 开启Redis选项
    enable-cache: false
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 10

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# 权限校验相关信息
permission:
  secret-key: X0g1UAH1Gp5cDvIiEVf0bvAuHeFj7e8t
  subject: BUSSINESS-PLATFORM
# 平台工具相关
utils:
  thread-utils:
    core-thread-size: 4
    max-thread-size: 8
    keep-alive-time: 1000

# 自动生成数据
data-generation:
  enable: false
  data-num: 1000

mail:
  mail-account: jorybeast97@126.com
  mail-password: NLJGPBEEAHOVJBYJ
  IMAP:
  POP3: